pull_request_rules:
    - name: Automatic merge on CI success and review
      conditions:
          - label!=dont-merge
          - label!=squash
          - '#approved-reviews-by>=1'
      actions:
          merge:
              method: merge

    - name: Automatic squash on CI success and review
      conditions:
          - label!=dont-merge
          - label=squash
          - '#approved-reviews-by>=1'
      actions:
          merge:
              method: squash
              commit_message_template: |
                  {{ title }} (#{{ number }})

                  {{ body }}
