packages:
    - packages/*
    - docs

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - '@changesets/apply-release-plan@8.1.0'
    - '@changesets/changelog-github@1.0.1'
    - '@changesets/cli@3.0.2'
    - '@changesets/get-github-info@1.0.1'
    - '@changesets/git@4.0.1'
    - '@changesets/read@1.0.1'
    - eslint@10.10.0

allowBuilds:
    '@swc/core': true
    esbuild: true
    core-js: false
    msw: false

overrides:
    serialize-javascript: ^7.0.3
    image-size: npm:image-size-next@^2.1.0
