import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
    docsSidebar: [
        {
            type: 'category',
            label: 'Guides',
            items: [
                'getting-started',
                'packages',
                { type: 'doc', id: 'client', label: 'Creating a client' },
                'frappe-versions',
                'authentication',
                'middleware',
                'errors',
                'testing',
                'realtime',
                'typescript',
                'codegen',
                'migration-client-4',
                'migration-codegen-2',
            ],
        },
        {
            type: 'category',
            label: 'Modules',
            items: [
                'modules/auth',
                'modules/database',
                'modules/rpc',
                'modules/files',
                'modules/search',
                'modules/permissions',
                'modules/workflow',
                'modules/desk',
                'modules/reports',
                'modules/site',
            ],
        },
        {
            type: 'category',
            label: 'Client API',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'api',
                },
            ],
        },
        {
            type: 'category',
            label: 'Codegen API',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'api-codegen',
                },
            ],
        },
    ],
}

export default sidebars
